USE AM_Grupo5;

-- Insertar datos base en TIPO_DE_LOCALIDAD
INSERT INTO TIPO_DE_LOCALIDAD (Nombre) VALUES 
('PARAJE'),
('PUEBLO'),
('CIUDAD');

-- Insertar datos base en TIPO_DE_CIRCUITO
INSERT INTO TIPO_DE_CIRCUITO (Nombre) VALUES 
('RURAL'),
('URBANO');

-- Insertar datos base en TIPO_DE_VOTO
INSERT INTO TIPO_DE_VOTO (Nombre) VALUES 
('ANULADO'),
('EN BLANCO');

-- Insertar datos base en TIPO_DE_OBSERVACION
INSERT INTO TIPO_DE_OBSERVACION (Nombre) VALUES 
('SIMPLE'),
('POR IDENTIDAD');

-- Insertar datos base en ROL_DE_COMISION_RECEPTORA
INSERT INTO ROL_DE_COMISION_RECEPTORA (Nombre) VALUES 
('PRESIDENTE'),
('SECRETARIO'),
('VOCAL'),
('SUPLENTE');

-- Insertar datos base en CARGO_POLITICO
INSERT INTO CARGO_POLITICO (Nombre) VALUES 
('PRESIDENTE'),
('VICEPRESIDENTE');

-- Insertar datos base en DEPARTAMENTO
INSERT INTO DEPARTAMENTO (Nombre) VALUES 
('ARTIGAS'),
('CANELONES'),
('CERRO LARGO'),
('COLONIA'),
('DURAZNO'),
('FLORIDA'),
('FLORES'),
('LAVALLEJA'),
('MALDONADO'),
('MONTEVIDEO'),
('PAYSANDÚ'),
('RÍO NEGRO'),
('RIVERA'),
('ROCHA'),
('SALTO'),
('SAN JOSÉ'),
('SORIANO'),
('TACUAREMBÓ'),
('TREINTA Y TRES');