USE AM_Grupo5;

INSERT INTO TIPO_DE_LOCALIDAD (Nombre) VALUES 
("PARAJE"),
("PUEBLO"),
("CIUDAD");

INSERT INTO TIPO_DE_CIRCUITO (Nombre) VALUES 
("RURAL"),
("URBANO");

INSERT INTO TIPO_DE_VOTO (Nombre) VALUES 
("ANULADO"),
("EN BLANCO");

INSERT INTO TIPO_DE_OBSERVACION (Nombre) VALUES 
("SIMPLE"),
("POR IDENTIDAD");

INSERT INTO ROL_DE_COMISION_RECEPTORA (Nombre) VALUES 
("PRESIDENTE"),
("SECRETARIO"),
("VOCAL"),
("SUPLENTE");

INSERT INTO CARGO_POLITICO (Nombre) VALUES 
("PRESIDENTE"),
("VICEPRESIDENTE");

INSERT INTO DEPARTAMENTO (Nombre) VALUES 
("ARTIGAS"),
("CANELONES"),
("CERRO LARGO"),
("COLONIA"),
("DURAZNO"),
("FLORIDA"),
("FLORES"),
("LAVALLEJA"),
("MALDONADO"),
("MONTEVIDEO"),
("PAYSANDÚ"),
("RÍO NEGRO"),
("RIVERA"),
("ROCHA"),
("SALTO"),
("SAN JOSÉ"),
("SORIANO"),
("TACUAREMBÓ"),
("TREINTA Y TRES");